### ISSUE TITLE
Make voila and jupyterlab optional dependencies.

### ISSUE THREAD

**Issue by yakutovicha** [CasperWA/voila-optimade-client#183]
When I was trying to build the AiiDAlab environment, I realized that the `optimade-client` depends on Jupyter Lab and voila which, in turn, require tornado to be higher than 5.0. This makes it impossible to build a consistent environment, as AiiDA requires tornado to be strictly lower than 5.0.

The possible solution would be to make those dependencies optional and install them only when the `[voila]` extra is set.

**Comment by CasperWA** [comment]
The cons here being that the nice and simple "pip install and run `optimade-client`" won't work anymore. One would instead have to specifically add the the extra to the install to make it work.

This I find acceptable, and will respect the package, since it essentially has two purposes:
1. Provide Jupyter widgets to be used in Jupyter notebooks.
2. Provide a Voilà application that can be run locally (and in Docker).

This change will simply make the split of these purposes explicit.
