### ISSUE TITLE
Do not show the periodic table by default

### ISSUE THREAD

**Issue by csadorf** [CasperWA/voila-optimade-client#201]
The latest version of the client shows the periodic table by default which I find really overwhelming and reduces the UI quality significantly. Embedded into the QE app I can't even see the whether a given query yielded any results because the screen is completely covered by the table (see screenshot).
![Screen Shot 2020-11-03 at 3 27 07 PM](https://user-images.githubusercontent.com/1441208/97997261-131a2c80-1de9-11eb-9a01-5e285375a794.png)
**Proposal**: Make the table an accordion widget that can be opened if desired.

**Comment by CasperWA** [comment]
Great to see some feedback on the new periodic table widget!

Since I would like to avoid having the accordion in by default, would you be fine with implementing this solution when passing `embedded=True`? Or would you insist on a separate wrapper accordion flag?

My motivation for including this option in the `embedded` flag, is the suspicion that this issue is mainly prevalent for such situations and not really an issue in any other application of the widget. However, I may be wrong about this - but adding another flag later is not a big issue.

**Comment by csadorf** [comment]
1. I honestly believe that showing the table by default is overkill in most situations. 
2. I don't think overloading the `embedded` option with this is a good idea, because it makes it more difficult to control the widget behavior in various circumstances. I don't expect that the use cases of "wanting to show the table" and "wanting to embed the widget" are always aligned.

Since you seem to be keen on keeping the table on by default, how about we place it in a container and toggle its visibility with a checkbox or a button and also connect it to a widget trait such that we can hide it by default if desired?

**Comment by CasperWA** [comment]
> 1. I honestly believe that showing the table by default is overkill in most situations.

I don't completely agree. In the application's natural form, the table is extremely useful, since it's the main form of filtering for chemical elements.
That said, I like your suggestion of a "toggle button".

> 2. I don't think overloading the `embedded` option with this is a good idea, because it makes it more difficult to control the widget behavior in various circumstances. I don't expect that the use cases of "wanting to show the table" and "wanting to embed the widget" are always aligned.

I don't completely agree with this.
The `embedded` flag is per definition an overloaded option, since it's supposed to toggle whether the widget is embedded or not, in-/excluding any options that optimizes it for embedding.

In terms of the "toggle button" this would then mean that `embedded=True` would dictate the default is to _not_ show the table, while for `True` the default _is_ to show the table.

> Since you seem to be keen on keeping the table on by default, how about we place it in a container and toggle its visibility with a checkbox or a button and also connect it to a widget trait such that we can hide it by default if desired?

Seems reasonable.

**Comment by csadorf** [comment]
Sounds good! 👍
