### ISSUE TITLE
Results do not appear to be meaningfully ordered - Add sorting option

### ISSUE THREAD

**Issue by csadorf** [CasperWA/voila-optimade-client#207]
Performing a search on the MaterialsProject website directly, such as this one: https://materialsproject.org/#search/materials/{%22nelements%22%3A4%2C%22elements%22%3A%22Li-O-P-Fe%22} yields the structure with formula **LiFePO4** as the first result which makes sense, because it exactly matches the elements that were selected for search.

Performing the same search via the OPTIMADE client yields the following results as the first batch:
![Screen Shot 2020-11-05 at 9 39 40 AM](https://user-images.githubusercontent.com/1441208/98217527-e716bc80-1f4a-11eb-80d4-a4529705302d.png)
While the first result looks promising, it does not look like results are ordered by *the number of matching elements*, which makes the search impractical, because as a user I would either need to scroll through the remaining _71,598_  matching results or start excluding basically *all other potentially matching elements*.

**Suggestion**: Order results by the number of matched elements.

**Comment by csadorf** [comment]
Addendum: Enabling the "Structure must ex-/include ALL chosen elements" check-box alleviates the problem, but I think returning results in a better sorted order would still be preferable.

**Comment by CasperWA** [comment]
> Addendum: Enabling the "Structure must ex-/include ALL chosen elements" check-box alleviates the problem (...)

Indeed, I was just going to say this :)

> (...) but I think returning results in a better sorted order would still be preferable.

Sure. I can add the `sort` query parameter to the query. The issue is then understanding exactly what you want to sort for.
I think generally I want to add another functionality where one can choose exactly this. I thought I had an issue for this, but it seems I don't. But I'll create one, thanks!

**Comment by csadorf** [comment]
> > Addendum: Enabling the "Structure must ex-/include ALL chosen elements" check-box alleviates the problem (...)
> 
> Indeed, I was just going to say this :)

_Alleviates_, but does not actually _solve_ it unfortunately. I so far have not been able to find the specific structure that I am looking for.

> > (...) but I think returning results in a better sorted order would still be preferable.
> 
> Sure. I can add the `sort` query parameter to the query. The issue is then understanding exactly what you want to sort for.
> I think generally I want to add another functionality where one can choose exactly this. I thought I had an issue for this, but it seems I don't. But I'll create one, thanks!

Searching by the number of matching elements appears like an intuitive approach that works well for the MaterialsProject. Compare with a standard search engine that would try to return results that match as many keywords as possible first as opposed to results that just contain any of the provided keywords.

Having some optional parameter for adjusting the search to once needs might be a nice feature, but I would consider that less urgent than employing some reasonable sort order right now.

**Comment by CasperWA** [comment]
The way results are displayed are a direct reflection of the server. If we want different sorting, we will have to get this by using the `sort` query parameter when searching, as I wrote above. This will have to change according to "what makes sense" for the given search parameters - and since this quickly becomes quite involved and difficult to assess, I'd rather have an extra "sort" dropdown or similar to post-sort the structures by, as any other search engine also has.

We can indeed also try to understand what should be sorted by based on the user filter parameters, but again, I feel this quickly becomes a black hole of time that will yield very little compared to the "minor" addition of a "sort by" dropdown.

**Comment by csadorf** [comment]
> The way results are displayed are a direct reflection of the server. If we want different sorting, we will have to get this by using the `sort` query parameter when searching, as I wrote above. This will have to change according to "what makes sense" for the given search parameters - and since this quickly becomes quite involved and difficult to assess, I'd rather have an extra "sort" dropdown or similar to post-sort the structures by, as any other search engine also has.
> 
> We can indeed also try to understand what should be sorted by based on the user filter parameters, but again, I feel this quickly becomes a black hole of time that will yield very little compared to the "minor" addition of a "sort by" dropdown.

Fair enough.
