### ISSUE TITLE
New export formats

### ISSUE THREAD

**Issue by giovannipizzi** [CasperWA/voila-optimade-client#30]
I suggest adding a few more export formats.
In particular, XSF? Maybe some more (you could check what ASE supports for instance)?

**Comment by CasperWA** [comment]
Sure.
Since we can convert to ASE, we can use all of their conversion-implementations as well. However, the caveat being that we first have to go through ASE. So while we can control (in `optimade-python-tools`) how much information is lost in the conversion to an ASE `Atoms`, we do not know how much is lost afterwards.

The same for `pymatgen`, which is also supported.

**Comment by CasperWA** [comment]
Closed in #37
